-- Generated by Claude.ai/Sonnet 4.6

INSERT INTO department (name) VALUES
('Engineering'),
('HR');

INSERT INTO employee (name, birth_date, department_id) VALUES
('Alice', '1990-03-15', 1),
('Bob', '1985-07-22', 1),
('Carol', '1992-11-01', 2);

INSERT INTO manages (employee_id, department_id) VALUES
(1, 1),
(3, 2);

INSERT INTO project (name, budget) VALUES
('System Redesign', 50000.00),
('Recruitment Tool', 20000.00);

INSERT INTO assignment (employee_id, project_id, hours_worked) VALUES
(1, 1, 40),
(2, 1, 30),
(3, 2, 20),
(1, 2, 10);
