CREATE TABLE IF NOT EXISTS patient (
    id INT AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    birth_date DATE,

    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS doctor (
    id INT AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    specialty VARCHAR(100) NOT NULL,

    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS ward (

);

CREATE TABLE IF NOT EXISTS admission ();
