CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    major VARCHAR(50) NOT NULL,
    year INT NOT NULL,

    PRIMARY KEY (id)
);
