-- Generated by Claude.ai/Sonnet 4.6

INSERT INTO patient (name, birth_date) VALUES
('Alice Brown', '1990-04-12'),
('Bob Smith', '1975-08-23'),
('Carol White', '2000-01-05');

INSERT INTO doctor (name, specialty) VALUES
('Dr. Adams', 'Cardiology'),
('Dr. Patel', 'Neurology');

INSERT INTO ward (name, total_beds) VALUES
('Cardiology', 20),
('Neurology', 15);

INSERT INTO admission (patient_id, doctor_id, ward_id, date, discharge_date) VALUES
(1, 1, 1, '2024-01-10', '2024-01-15'),
(2, 1, 1, '2024-02-01', NULL),
(1, 2, 2, '2024-03-05', '2024-03-08'),
(3, 2, 2, '2024-03-10', NULL);
